config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :experiences
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :experiences
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable,  :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :experiences, dependent: :destroy

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_exp, only: [:show]

  def index
    @search = params[:search_term] if  !params[:search_term].nil?
    @city = params[:city] if  !params[:city].nil?
    @category = params[:category]

    @experiences = Experience.all

    # filter on category
    if @category.present?
      @experiences = @experiences.where(category_id: params[:category])
    end

    # filter on title/description
    if @search.present?
      @experiences = @experiences.where("LOWER(title) = ?", @search.downcase)
    end

    # filter on city
    if @city.present?
      @experiences = @experiences.where("LOWER(city) = ?", @city.downcase)
    end

  end

  def show

  end

  def new
    @experience = Experience.new

  end

  def create
    @experience = Experience.new(exp_params)
    @experience.user_id = current_user.id
    @experience.save!

    redirect_to experience_path(@experience)
  end

private

  def set_exp
    @experience = Experience.find(params[:id])
  end

  def exp_params
    params.require(:experience).permit(:startexperience, :city, :category_id, :title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home]



  def home
    @background = ["girl-alone-paintings.jpg", "concert.jpg", "classical_music.jpg"].sample
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiences/index.html.erb
<!-- app/views/experience/index.html.erb -->
<div class="wrapper" id="index-all-exp">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12" >
        <h2>Try with Two</h2>
        <h4>You would like to check out
          a [movie/restaurant/exhibition/concert] </h4>
          <h5>but don't fancy to go alone? </h5>
          <h3> Find somebody with <strong>exactly</strong> the same idea! </h3>
        </div>
      </div>
    </div>
  </div>

<!-- <SEARCH> -->
<div class="container">
   <div class="row">
    <div class="col-sm-12">
      <%= render "shared/search-engine" %>
    </div>
  </div>
</div>


<!-- <experience cards> -->
  <div class="wrapper" id="exp-index-wrapper">
    <div class="container">
      <div class="row">

        <% @experiences.each do |exp| %>
        <div class="col-xs-12 col-sm-4">

          <div  class="card-background">
          <div class="card">

            <%= link_to experience_path(exp) do %>

            <div class="card-title">
              <h3> <%= exp.title%> </h3>
            </div>
            <br>
            <br>
            <div class="card-description">
              <p><%= exp.description%> </p>
              <p>On <%=exp.startexperience.strftime('%a, %v')%>at <%=exp.startexperience.strftime('%R') %> </p>

            </div>

            <div class="card-city">
               <h4><%= exp.city%> </h4>
            </div>

            <div id="prof-pic-index">
                <%= image_tag exp.user.facebook_picture_url, id: "creator-avatar", class: "card-user avatar"%>
            </div>

            <% end %>
          </div>
          </div>
        </div>
        <%end%>
      </div>
    </div>
  </div>

  <br>
  <%= render 'shared/subfooter'%>
  <br>

app/views/experiences/new.html.erb
<div class="wrapper">
  <div class="container">

   <div class="row">
    <div class="col-xs-offset-3 col-xs-6">
     <h4> Hi <%= current_user.first_name %>, </h4>
     <h2> would you like to propose an activity? </h2>
     <h6> Let's go!</h2>
     <br>
     </div>
   </div>

   <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div id="create_new_proposal">

        <%= form_for(@experience) do |f| %>

          <div class="">
              <h4> Category</h4>
          </div>
          <div class="">
                <%= f.collection_select(:category_id, Category.all, :id, :name) %>
          </div>

          <div class="row">

         <div class="">
              <h4> Title</h4>
              <p> Give your activity a title [max 100 char.]</p>
          </div>
        <div class="">
        <%= f.text_field :title, placeholder: "what?", style: "width: 300px; height: 40px;"%>
        </div>

        <div class="">
            <h4> Description</h4>
            <p> What does your activity entail more exactly? </p>
        </div>
        <div class="">
        <%= f.text_area :description, placeholder: "what exactly?", style: "width: 300px; height: 150px;" %>
        </div>

          <div class="">
            <h4> url / link of event-page</h4>
        </div>
        <div class="">
        <%= f.text_field :url, style: "width: 300px; height: 40px;" %>
           </div>

        <div class="">
          <h4>Date with start time:</h4>
        </div>
        <div class="">
        <%= datetime_select(:experience, :startexperience, options = {min: Date.today}) %>
        </div>

        <div class="">
          <h4>(probable) end time:</h4>
        </div>
        <div class="">
          <%=f.time_select :stopexperience, :ignore_date => true %>
        </div>

        <div class="">
          <h4>Address</h4>
        </div>
          <div class="">
        <%= f.label :address %>
        <%= f.text_field :address, placeholder: "street & number?"%>
          </div>

        <div class="">
          <h4>City</h4>
        </div>
          <div class="">
        <%= f.label :city %>
        <%= f.text_field :city, placeholder: "where?"%>
          </div>

        <%= f.hidden_field :user_id%>

        <br>
        <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
 </div>
</div>

app/views/experiences/show.html.erb
<!-- app/views/experiences/show.html.erb -->

<div id="show-title-wrapper">
  <div id="title-exp">
    <h3> Would you like to join <strong> <%= @experience.user.first_name%> </strong> to:</h3>
    <h2><%= @experience.title%> </h2>
  </div>

  <div id="short-profile-creator">
    <%= image_tag @experience.user.facebook_picture_url, id: "creator-avatar", class: "avatar-large" %>
    <h3><%= @experience.user.first_name%>'s profile</h3>
    <%= link_to 'see profile', experiences_path %>
  </div>

</div>


<div class="wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-sm-9">


              <div id="exp-show-card">

                <div class="card-title" id="card-title-show">
                  <h3> City: <%= @experience.city%> </h3>
                </div>


                <div class="card-description" id="card-description-show">

                  <h4>Description: <%= @experience.description%> </h4>
                  <p>link: <%= @experience.url %> </p>
                  <p>address: <%= @experience.address %> </p>
                  <h3>On <%= @experience.startexperience.strftime('%a, %v')%>
                   at <%= @experience.startexperience.strftime('%R') %> </h3>
                  <p>Expected duration time: <%= @experience.stopexperience%> </p>
                </div>
              </div>

      </div>


      <div class="col-sm-9">

         <br>
          <%= render 'shared/subfooter'%>
          <br>

    </div>
   </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Actor" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">



    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image:url('<%= image_path @background %>')">

  <div class="banner-content" id="homepage-card">

    <h1>Try with Two</h1>
    <h2>You would like to check out a [movie/restaurant/exhibition/concert] </h2>
    <h3>but don't fancy to go alone? </h3>
    <h2> Find somebody with <strong>exactly</strong> the same idea! </h2>
  <br>
    <p>Have an extra ticket?</p>
    <p> Propose an outing and find somebody who would also love to go!</p>
    <%= link_to 'check out the proposals', experiences_path, class: "btn btn-default btn-lg" %>

  </div>
</div>

app/views/profiles/show.html.erb
<div class="show-background"></div>
<div class="padded">
  <div class="profile-header-wrapper">
    <div class="profile-header-container text-center">
      <div class="profile-header-infos">

        <% if current_user.facebook_picture_url %>
        <%= image_tag current_user.facebook_picture_url, class:"avatar-large", data: { toggle: 'dropdown'} %>
        <% else %>
        <%= image_tag 'placeholder.png', class: "avatar",  data: { toggle: 'dropdown'}  %>
        <% end %>
        <h3><%= current_user.first_name %> <%= current_user.last_name %></h3>
      </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

    <div class="navbar-left">
        <%= link_to root_path, class: 'navbar-wagon-brand' do %>
          <div> <%= image_tag 'logo.png',  class:'img-responsive', width: '80px' %></div>
        <% end %>
      </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
           <% if current_user.facebook_picture_url %>
              <%= image_tag current_user.facebook_picture_url, class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% else  %>
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Propose an outing"), new_experience_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search-engine.html.erb
<div id="search-and-btn-display">
   <!-- <input-field-for tags> -->
  <%= form_tag experiences_path, method: "get" do %>
   <%= text_field_tag(:search_term, @search, placeholder: "what?") %>
   <!-- <city-dropdown> -->
    <%= text_field_tag(:city, nil, placeholder: "where?") %>
   <!-- <category-dropdown> -->
   <%= collection_select nil, :category, Category.all, :id, :name, prompt: "All categories" %>
   <!-- <button> -->
   <%= submit_tag("Search", class: 'btn btn-default btn-lg', id: "search-btn") %>
   <% end %>
 </div>

app/views/shared/_subfooter.html.erb
<div id="subfoot-wrapper">
        <div id="subfoot-card">
          <h3>Like to meet somebody new, </h3>
          <h3>while doing something you like?</h3>
          <%= link_to new_experience_path do %>
          <h3>
            <span class="label label-danger">Propose an Outing</span>
          </h3>
          <% end %>
        </div>
</div>